export const userSchema = {
  type: 'object',
  properties: {
    mode: {
      type: 'string',
      enum: ['wedding', 'birth', 'death']
    },
    personalLastName: { type: 'string' },
    personalFirstName: { type: 'string' },
    personalMiddleName: { type: 'string' },
    personalPhoneNumber: { type: 'string' },
    personalNumberOfPassport: { type: 'string' },
    personalAddress: { type: 'string' },
    citizenLastName: { type: 'string' },
    citizenFirstName: { type: 'string' },
    citizenMiddleName: { type: 'string' },
    citizenBirthDate: { type: 'string' },
    citizenNumberOfPassport: { type: 'string' },
    citizenGender: { type: 'string' },
    citizenAddress: { type: 'string' },
    dateOfMarriage: { type: ['string', 'null'] },
    newLastName: { type: ['string', 'null'] },
    anotherPersonLastName: { type: ['string', 'null'] },
    anotherPersonFirstName: { type: ['string', 'null'] },
    anotherPersonMiddleName: { type: ['string', 'null'] },
    birth_of_anotoherPerson: { type: ['string', 'null'] },
    anotherPersonPassport: { type: ['string', 'null'] },
    birth_place: { type: ['string', 'null'] },
    birth_mother: { type: ['string', 'null'] },
    birth_father: { type: ['string', 'null'] },
    birth_grandpa: { type: ['string', 'null'] },
    birth_grandma: { type: ['string', 'null'] },
    death_dateOfDeath: { type: ['string', 'null'] },
    death_placeOfDeath: { type: ['string', 'null'] }
  },
  required: [
    'mode',
    'personalLastName',
    'personalFirstName',
    'personalMiddleName',
    'personalPhoneNumber',
    'personalNumberOfPassport',
    'personalAddress',
    'citizenLastName',
    'citizenFirstName',
    'citizenMiddleName',
    'citizenBirthDate',
    'citizenNumberOfPassport',
    'citizenGender',
    'citizenAddress',
    'dateOfMarriage',
    'newLastName',
    'anotherPersonLastName',
    'anotherPersonFirstName',
    'anotherPersonMiddleName',
    'birth_of_anotoherPerson',
    'anotherPersonPassport',
    'birth_place',
    'birth_mother',
    'birth_father',
    'birth_grandpa',
    'birth_grandma',
    'death_dateOfDeath',
    'death_placeOfDeath'
  ]
};
